version: "3.7"

services:
  api:
    image: node-elasticsearch-api
    container_name: tut-node
    build: ./backend
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - NODE_PORT=4000
      - ELASTIC_URL=http://elasticsearch:9200
    volumes:
      - ./backend:/usr/src/app/quotes
    command: npm run start
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - esnet

  elasticsearch:
    container_name: tut-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - esnet
networks:
  esnet:
